### ISSUE TITLE
1.22.0 has broken typescript bindings (not an issue outside of typescript usage)

### ISSUE THREAD

**Issue by nightnei** [apostrophecms/sanitize-html#333]
Can't build project after upgrading version from 1.21.1 to 1.22.0.

```
node_modules/@types/domutils/index.d.ts:6:10 - error TS2614: Module '"../../../../../../../../Users/UserName/projects/project/node_modules/domhandler/lib"' has no exported member 'DomElement'. Did you mean to use 'import DomElement from "../../../../../../../../Users/UserName/projects/nc/namp-cms-content-provider/node_modules/domhandler/lib"' instead?

6 import { DomElement } from "domhandler";
           ~~~~~~~~~~

node_modules/@types/htmlparser2/index.d.ts:17:10 - error TS2614: Module '"../../../../../../../../Users/UserName/projects/project/node_modules/domhandler/lib"' has no exported member 'DomElement'. Did you mean to use 'import DomElement from "../../../../../../../../Users/UserName/projects/project/node_modules/domhandler/lib"' instead?

17 export { DomElement, DomHandlerOptions, DomHandler, Element, Node } from 'domhandler';
            ~~~~~~~~~~

node_modules/@types/sanitize-html/index.d.ts:17:10 - error TS2459: Module '"../../../../../../../../Users/UserName/projects/project/node_modules/htmlparser2/lib"' declares 'Options' locally, but it is not exported.

17 import { Options } from "htmlparser2";
            ~~~~~~~

  node_modules/htmlparser2/lib/index.d.ts:5:14
    5 declare type Options = ParserOptions & DomHandlerOptions;
                   ~~~~~~~
    'Options' is declared here.
```

**Comment by nightnei** [comment]
@boutell it looks like a similar issue to https://github.com/apostrophecms/sanitize-html/issues/320
Look at it, please.

**Comment by boutell** [comment]
All tests are passing — need to know how to reproduce this issue, as a failing test PR or as a simple test project demonstrating it.

**Comment by boutell** [comment]
(All tests are passing in node 12.)

**Comment by dmattia** [comment]
I am also getting this issue. From the output from @nightnei, it seems like both you and I are using typescript with @types/sanitize-html v1.20.2. So I believe the issue is with the typed library, not this module itself

**Comment by dmattia** [comment]
Looks like `Options` in the typed lib should be changed to `Parser`

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1c82c17ce10411086f2bb56aa91a1c9246463bfc/types/sanitize-html/index.d.ts#L67

@boutell do you also mantain typed version?

**Comment by nightnei** [comment]
@dmattia, @boutell  I have found the problem.

"@types/sanitize-html" uses dependency - "@types/htmlparser2": "*".
but now latest verison of `htmlparser2` -`4.1.0` uses own typeshttps://github.com/fb55/htmlparser2/compare/v4.0.0...v4.1.0#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R24

so now you can remove `@types/sanitize-html` and everything will be fine :)

**Comment by michaelfarrell76** [comment]
solution above does not work for us because our monorepo has but htmlparser2 and sanitize-html installed. if we remove `@types/sanitize-html` then we get `Could not find a declaration file for module 'sanitize-html'.`

**Comment by theFroh** [comment]
Also chiming in -- @nightnei's solution unfortunately also doesn't resolve this for us. Without `@types/sanitize-html`, tsc spits the dummy when compiling: `Could not find a declaration file for module 'sanitize-html'` 

This is with Typescript `3.8.3`. I'd guess that the proposed solution relies on a JS inference option being set?

Either way, once I install `@types/sanitize-html@1.22.0`, the issue then becomes a mess of:
```
Module '"../../domhandler/lib"' has no exported member 'DomElement'
Module '"../../htmlparser2/lib"' declares 'Options' locally, but it is not exported.
```

For now I'll keep the installed version pinned prior to `1.22`.

**Comment by michaelfarrell76** [comment]
can this issue be re opened plz?

**Comment by boutell** [comment]
Sure, reopened and the title clarified. This isn't something we can resolve in-house as we don't do typescript but happy to help release whatever is decided upon.

**Comment by michaelfarrell76** [comment]
our solution here was to set `"skipLibCheck": true,` in our tsconfig. This is obviously not ideal but for those that want a quick fix it works

**Comment by dsyncerek** [comment]
I've made a PR to `@types/sanitize-html` https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43870, which should resolve the issue with `htmlparser2` types.
